### ISSUE TITLE
Designers need html descriptions in attributes

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/designs#22]

**Comment by graemeblair** [comment]
Markdown not HTML?

**Comment by jaspercooper** [comment]
Maybe we can move to that, but for now it's html. If you go to http://shiny.declaredesign.org/inspector/ and bring in the two-way factorial from the library you'll see this desc at the top:

> A two way factorial design with a size `N`, main effects `beta_A` and `beta_B`, and interaction `beta_AB`.
> Estimand is the average interaction effect.

[That comes from here.](https://github.com/DeclareDesign/designs/blob/dc749c08b37b746b028778924691443cf77406d5/R/two_way_factorial.R#L64)

**Comment by jaspercooper** [comment]
Done for all designers currently in library that had shiny capability
