### ISSUE TITLE
Vignettes (crossover_design.Rmd) not compiling

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/designs#27]
Travis says: 

```r
Quitting from lines 34-35 (crossover_designer.Rmd) 
Error: processing vignette 'crossover_designer.Rmd' failed with diagnostics:
Please only send design objects to diagnose_design.
Execution halted
```

@medinali would you mind taking a look at some point this week?

**Comment by jaspercooper** [comment]
Found the bug: `make_vignette()` needs to add () inside get_or_run_diagnosis:

`get_or_run_diagnosis(crossover_designer, sims = 10, bootstrap = FALSE)`
should be
`get_or_run_diagnosis(crossover_designer(), sims = 10, bootstrap = FALSE)`

**Comment by medinali** [comment]
done! 

Thanks, Jasper.
