### ISSUE TITLE
Migrate script for generating .RDS simulations to Shiny server

### ISSUE THREAD

**Issue by clabima** [DeclareDesign/designs#34]

**Comment by jaspercooper** [comment]
These functions and only these should be deleted from DesignLibrary and put into the shiny repo, and cleaned up:
- [ ] `get_or_run_diagnosis`
- [ ] `get_shiny_arguments`
- [ ] `get_constants`
- [ ] `expand_designer_shiny_args_text`
  - Depends upon `designer_default_args_text`, pulled in from DesignLibrary
- [ ] `get_shiny_diagnosis`
- [ ] `get_or_run_shiny_diagnosis`

**Comment by jaspercooper** [comment]
After this is done I will write the script to automate this
